using System;
using System.Collections.Generic;
using UnityEngine;

namespace BuildManagerKit
{
    /// <summary>
    /// A single environment variable baked into the build.
    /// </summary>
    [Serializable]
    public struct BuildVariable
    {
        public string key;
        public string value;

        public BuildVariable(string key, string value)
        {
            this.key = key;
            this.value = value;
        }
    }

    /// <summary>
    /// Runtime accessible description of how the currently running player was built.
    /// The asset is generated by Build Manager Kit into
    /// <c>Assets/Resources/BuildManagerKit/BuildInfo.asset</c> before every build and every
    /// time the active environment is switched inside the Editor, so the values are also
    /// correct in play mode.
    /// </summary>
    /// <example>
    /// <code>
    /// if (BuildInfo.Current.IsEnvironment("prod"))
    ///     Analytics.Enable();
    ///
    /// string api = BuildInfo.Current.GetVariable("api_url", "https://localhost");
    /// </code>
    /// </example>
    public sealed class BuildInfo : ScriptableObject
    {
        /// <summary>Resources relative path the generated asset lives at.</summary>
        public const string ResourcePath = "BuildManagerKit/BuildInfo";

        [SerializeField] internal string m_EnvironmentId = "editor";
        [SerializeField] internal string m_EnvironmentName = "Editor";
        [SerializeField] internal string m_ProfileId = string.Empty;
        [SerializeField] internal string m_Version = "0.0.0";
        [SerializeField] internal int m_BuildNumber;
        [SerializeField] internal string m_BuildTarget = string.Empty;
        [SerializeField] internal bool m_IsDevelopmentBuild;
        [SerializeField] internal string m_GitBranch = string.Empty;
        [SerializeField] internal string m_GitCommit = string.Empty;
        [SerializeField] internal bool m_GitDirty;
        [SerializeField] internal string m_BuildTimeUtc = string.Empty;
        [SerializeField] internal string m_BuildMachine = string.Empty;
        [SerializeField] internal List<BuildVariable> m_Variables = new List<BuildVariable>();

        private static BuildInfo s_Current;
        private Dictionary<string, string> m_Lookup;

        /// <summary>
        /// The build info for the running player. Never null: when no asset has been generated
        /// yet a neutral in-memory instance describing an "editor" build is returned.
        /// </summary>
        public static BuildInfo Current
        {
            get
            {
                if (s_Current != null)
                    return s_Current;

                s_Current = Resources.Load<BuildInfo>(ResourcePath);
                if (s_Current == null)
                {
                    s_Current = CreateInstance<BuildInfo>();
                    s_Current.name = "BuildInfo (Unbaked)";
                    s_Current.hideFlags = HideFlags.HideAndDontSave;
                }

                return s_Current;
            }
        }

        /// <summary>Identifier of the environment the player was built with, e.g. <c>"prod"</c>.</summary>
        public string EnvironmentId => m_EnvironmentId;

        /// <summary>Human readable environment name, e.g. <c>"Production"</c>.</summary>
        public string EnvironmentName => m_EnvironmentName;

        /// <summary>Identifier of the build profile that produced the player.</summary>
        public string ProfileId => m_ProfileId;

        /// <summary>Semantic version string that was applied to the player.</summary>
        public string Version => m_Version;

        /// <summary>Monotonically increasing build number (Android versionCode / iOS build number).</summary>
        public int BuildNumber => m_BuildNumber;

        /// <summary>Name of the <c>UnityEditor.BuildTarget</c> the player was built for.</summary>
        public string BuildTarget => m_BuildTarget;

        /// <summary>True when the player was built with development mode enabled.</summary>
        public bool IsDevelopmentBuild => m_IsDevelopmentBuild;

        /// <summary>Git branch the build was made from, empty when unavailable.</summary>
        public string GitBranch => m_GitBranch;

        /// <summary>Short git commit hash the build was made from, empty when unavailable.</summary>
        public string GitCommit => m_GitCommit;

        /// <summary>True when the working copy had uncommitted changes at build time.</summary>
        public bool GitDirty => m_GitDirty;

        /// <summary>UTC build timestamp in round-trip ("o") format.</summary>
        public string BuildTimeUtcRaw => m_BuildTimeUtc;

        /// <summary>Name of the machine that produced the build.</summary>
        public string BuildMachine => m_BuildMachine;

        /// <summary>All environment variables baked into the build.</summary>
        public IReadOnlyList<BuildVariable> Variables => m_Variables;

        /// <summary>UTC build timestamp, or <see cref="DateTime.MinValue"/> when unavailable.</summary>
        public DateTime BuildTimeUtc =>
            DateTime.TryParse(m_BuildTimeUtc, null, System.Globalization.DateTimeStyles.RoundtripKind, out var parsed)
                ? parsed
                : DateTime.MinValue;

        /// <summary>Short display string, e.g. <c>"1.4.2+118 (prod)"</c>.</summary>
        public string ShortVersionString => $"{m_Version}+{m_BuildNumber} ({m_EnvironmentId})";

        /// <summary>Case-insensitive comparison against the build environment id.</summary>
        public bool IsEnvironment(string environmentId) =>
            string.Equals(m_EnvironmentId, environmentId, StringComparison.OrdinalIgnoreCase);

        /// <summary>Reads a baked environment variable, returning <paramref name="fallback"/> when absent.</summary>
        public string GetVariable(string key, string fallback = "")
        {
            if (string.IsNullOrEmpty(key))
                return fallback;

            if (m_Lookup == null)
            {
                m_Lookup = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                for (var i = 0; i < m_Variables.Count; i++)
                {
                    var variable = m_Variables[i];
                    if (!string.IsNullOrEmpty(variable.key))
                        m_Lookup[variable.key] = variable.value;
                }
            }

            return m_Lookup.TryGetValue(key, out var value) ? value : fallback;
        }

        /// <summary>Reads a baked environment variable as a boolean.</summary>
        public bool GetBoolVariable(string key, bool fallback = false) =>
            bool.TryParse(GetVariable(key, fallback.ToString()), out var value) ? value : fallback;

        /// <summary>Reads a baked environment variable as an integer.</summary>
        public int GetIntVariable(string key, int fallback = 0) =>
            int.TryParse(GetVariable(key, fallback.ToString()), out var value) ? value : fallback;

        /// <summary>Reads a baked environment variable as a float.</summary>
        public float GetFloatVariable(string key, float fallback = 0f) =>
            float.TryParse(GetVariable(key, fallback.ToString(System.Globalization.CultureInfo.InvariantCulture)),
                System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var value)
                ? value
                : fallback;

        internal void InvalidateLookup() => m_Lookup = null;

        private void OnEnable()
        {
            m_Variables ??= new List<BuildVariable>();
            m_Lookup = null;
        }

        public override string ToString() =>
            $"{m_Version}+{m_BuildNumber} [{m_EnvironmentId}/{m_BuildTarget}] {m_GitBranch}@{m_GitCommit}{(m_GitDirty ? "*" : string.Empty)}";
    }
}
