using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace BuildManagerKit.Editor
{
    /// <summary>CI systems the kit can generate a ready to run pipeline definition for.</summary>
    public enum CiProvider
    {
        GitHubActions = 0,
        GitLabCi = 1,
        Jenkins = 2,
        ShellScript = 3
    }

    /// <summary>
    /// Generates pipeline definitions wired to this project's profiles and environments, so the
    /// jump from "builds on my machine" to "builds on CI" is a copy of one file.
    /// </summary>
    public static class CiTemplateGenerator
    {
        /// <summary>Conventional file name for each provider.</summary>
        public static string GetDefaultFileName(CiProvider provider)
        {
            switch (provider)
            {
                case CiProvider.GitHubActions: return ".github/workflows/unity-build.yml";
                case CiProvider.GitLabCi: return ".gitlab-ci.yml";
                case CiProvider.Jenkins: return "Jenkinsfile";
                default: return "build.sh";
            }
        }

        /// <summary>Renders a pipeline definition for the given provider.</summary>
        /// <param name="provider">CI system to target.</param>
        /// <param name="profile">Profile the pipeline builds. Falls back to the first enabled one.</param>
        /// <param name="environment">Environment the pipeline builds with.</param>
        public static string Generate(CiProvider provider, BuildTargetProfile profile, BuildEnvironment environment)
        {
            var settings = BuildManagerSettings.Instance;

            profile ??= settings.GetEnabledProfiles().FirstOrDefault();
            environment ??= settings.ActiveEnvironment;

            var profileId = profile != null ? profile.Id : "windows";
            var environmentId = environment != null ? environment.Id : "prod";
            var unityVersion = Application.unityVersion;

            string template;
            switch (provider)
            {
                case CiProvider.GitLabCi:
                    template = k_GitLab;
                    break;
                case CiProvider.Jenkins:
                    template = k_Jenkins;
                    break;
                case CiProvider.ShellScript:
                    template = k_Shell;
                    break;
                default:
                    template = k_GitHub;
                    break;
            }

            return template
                .Replace("__PROFILE__", profileId)
                .Replace("__ENV__", environmentId)
                .Replace("__UNITY_VERSION__", unityVersion)
                .Replace("__PROJECT__", ProjectPaths.ProjectName);
        }

        /// <summary>
        /// Writes a pipeline definition into the project. Existing files are never silently
        /// overwritten; the caller decides after <paramref name="overwrite"/>.
        /// </summary>
        /// <returns>The absolute path written, or null when the file already existed.</returns>
        public static string Write(CiProvider provider, BuildTargetProfile profile, BuildEnvironment environment,
            bool overwrite = false)
        {
            var path = ProjectPaths.MakeAbsolute(GetDefaultFileName(provider));

            if (File.Exists(path) && !overwrite)
                return null;

            var directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory))
                Directory.CreateDirectory(directory);

            File.WriteAllText(path, Generate(provider, profile, environment));

            if (provider == CiProvider.ShellScript)
                TryMakeExecutable(path);

            AssetDatabase.Refresh();
            return path;
        }

        private static void TryMakeExecutable(string path)
        {
#if !UNITY_EDITOR_WIN
            try
            {
                ProcessRunner.Run("/bin/chmod", "+x " + ProcessRunner.Quote(path), null, 5000);
            }
            catch (Exception)
            {
                // Not being able to chmod is a cosmetic problem, not a failure.
            }
#endif
        }

        private const string k_GitHub = @"# Generated by Build Manager Kit for __PROJECT__.
# Requires a Unity licence in the repository secrets: UNITY_LICENSE, UNITY_EMAIL, UNITY_PASSWORD.
name: Unity Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: Build Manager Kit environment id
        default: __ENV__
        required: true

jobs:
  build:
    name: Build __PROFILE__
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0          # Build Manager Kit reads the git history for versioning

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-__PROFILE__-${{ hashFiles('Assets/**', 'Packages/**') }}
          restore-keys: Library-${{ runner.os }}-__PROFILE__-

      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          BMK_WEBHOOK_URL: ${{ secrets.BMK_WEBHOOK_URL }}
          ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          ANDROID_KEYALIAS_PASS: ${{ secrets.ANDROID_KEYALIAS_PASS }}
        with:
          unityVersion: __UNITY_VERSION__
          allowDirtyBuild: true
          buildMethod: BuildManagerKit.Editor.BuildCLI.Build
          customParameters: >-
            -bmkProfile __PROFILE__
            -bmkEnv ${{ github.event.inputs.environment || '__ENV__' }}
            -bmkResultFile ${{ github.workspace }}/build-result.json

      - name: Publish the build result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: build-result.json

      - uses: actions/upload-artifact@v4
        with:
          name: __PROFILE__-__ENV__
          path: Builds/
";

        private const string k_GitLab = @"# Generated by Build Manager Kit for __PROJECT__.
# Set UNITY_LICENSE_CONTENT (or use a floating licence server) in the project CI/CD variables.
stages:
  - build

variables:
  GIT_DEPTH: '0'                 # Build Manager Kit reads the git history for versioning
  UNITY_IMAGE: unityci/editor:ubuntu-__UNITY_VERSION__-linux-il2cpp-3

build:__PROFILE__:
  stage: build
  image: $UNITY_IMAGE
  cache:
    key: ""$CI_PROJECT_NAME-__PROFILE__""
    paths:
      - Library/
  before_script:
    - chmod +x ci/activate.sh && ./ci/activate.sh
  script:
    - >
      unity-editor
      -batchmode -nographics -quit=false
      -projectPath .
      -executeMethod BuildManagerKit.Editor.BuildCLI.Build
      -bmkProfile __PROFILE__
      -bmkEnv ${BMK_ENV:-__ENV__}
      -bmkResultFile build-result.json
      -logFile /dev/stdout
  artifacts:
    when: always
    paths:
      - Builds/
      - build-result.json
    reports:
      dotenv: build.env
";

        private const string k_Jenkins = @"// Generated by Build Manager Kit for __PROJECT__.
pipeline {
    agent any

    parameters {
        string(name: 'BMK_PROFILE', defaultValue: '__PROFILE__', description: 'Build Manager Kit profile id')
        string(name: 'BMK_ENV',     defaultValue: '__ENV__',     description: 'Build Manager Kit environment id')
        booleanParam(name: 'DRY_RUN', defaultValue: false,       description: 'Validate without building')
    }

    environment {
        UNITY = ""${tool 'Unity __UNITY_VERSION__'}/Editor/Unity""
        BMK_WEBHOOK_URL = credentials('bmk-webhook-url')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Validate') {
            steps {
                sh '''
                    ""$UNITY"" -batchmode -nographics -quit=false -projectPath ""$WORKSPACE"" \
                        -executeMethod BuildManagerKit.Editor.BuildCLI.ValidateAll \
                        -logFile /dev/stdout
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    ""$UNITY"" -batchmode -nographics -quit=false -projectPath ""$WORKSPACE"" \
                        -executeMethod BuildManagerKit.Editor.BuildCLI.Build \
                        -bmkProfile ""$BMK_PROFILE"" \
                        -bmkEnv ""$BMK_ENV"" \
                        -bmkResultFile ""$WORKSPACE/build-result.json"" \
                        ${DRY_RUN:+-bmkDryRun} \
                        -logFile /dev/stdout
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'build-result.json, Builds/**', allowEmptyArchive: true
        }
    }
}
";

        private const string k_Shell = @"#!/usr/bin/env bash
# Generated by Build Manager Kit for __PROJECT__.
# Usage: ./build.sh [profile] [environment]
set -euo pipefail

PROFILE=""${1:-__PROFILE__}""
ENVIRONMENT=""${2:-__ENV__}""
PROJECT_PATH=""$(cd ""$(dirname ""${BASH_SOURCE[0]}"")"" && pwd)""

# Point UNITY at your editor, or let the Hub default apply.
UNITY=""${UNITY:-/Applications/Unity/Hub/Editor/__UNITY_VERSION__/Unity.app/Contents/MacOS/Unity}""

""$UNITY"" \
    -batchmode \
    -nographics \
    -quit=false \
    -projectPath ""$PROJECT_PATH"" \
    -executeMethod BuildManagerKit.Editor.BuildCLI.Build \
    -bmkProfile ""$PROFILE"" \
    -bmkEnv ""$ENVIRONMENT"" \
    -bmkResultFile ""$PROJECT_PATH/build-result.json"" \
    -logFile /dev/stdout

echo ""Result written to $PROJECT_PATH/build-result.json""
";
    }
}
